from django.core.exceptions import ValidationError


def validate_phone(val):
    """Валидирует телефон"""

    pass